//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoc_Upload_File.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload_File_HinhAnh
    {
        public int id_HinhAnh { get; set; }
        public string path_HinhAnh { get; set; }
    }
}
